# Generated by Django 5.1.3 on 2024-12-02 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_follows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follows',
            old_name='created_at',
            new_name='followed_at',
        ),
    ]
