# Generated by Django 5.1.3 on 2024-12-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_created_at_follows_followed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='text_post',
            field=models.TextField(blank=True, null=True),
        ),
    ]
