# Generated by Django 5.1.3 on 2024-12-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_posts_text_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='image',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='video',
        ),
        migrations.AddField(
            model_name='posts',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='post_media'),
        ),
    ]
