# Generated by Django 5.1.3 on 2024-12-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_posts_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video')], max_length=10, null=True),
        ),
    ]
