# Generated by Django 5.1.3 on 2024-12-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0002_messages_recipient_alter_messages_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['-sent_at']},
        ),
        migrations.AlterField(
            model_name='messages',
            name='message_received',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message_sent',
            field=models.TextField(),
        ),
    ]
