# Generated by Django 5.1.3 on 2024-12-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0003_alter_messages_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message_received',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message_sent',
            field=models.TextField(null=True),
        ),
    ]
