# Generated by Django 5.1.3 on 2024-12-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0005_alter_messages_received_at_alter_messages_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messages',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
